- pyproject.toml
- setup.py
> Fixing pyLOM version to 1.2.0

- .github/workflows/package.yml
Missing specifing MPI version for workflow.
> Fix deployment workflow

- Converters/ensight2h5_wing.py
- pyLOM/POD/wrapper.py
- pyLOM/inp_out/__init__.py
- pyLOM/inp_out/io_ensight.py
- pyLOM/inp_out/io_ensight.pyx
- pyLOM/partition_table.py
- pyproject.toml
- requirements.txt
Adding the [Ensight Reader](https://github.com/tkarabela/ensight-reader) library to properly read more complex EnsightGold files, plus addition of an example.
Minor bug fixes.
> EnsightGold reading capabilities

- pyLOM/DMD/wrapper.py
- pyLOM/DMD/wrapper.pyx
> Adding chronos for profiling

- .github/workflows/package.yml
- README.md
Adding workflow dispatch and fixing setuptools on the automatic deployer for PyPi
> Adding workflow dispatch

- pyLOM/vmmath/src/svd.c
Changing to DGESVD and ZGESVD instead of DGESDD and ZGESDD when using OpenBLAS. 
Some minor bug fixes.
> OpenBLAS fixes

- pyLOM/inp_out/io_h5.py
- pyLOM/mesh.py
- pyLOM/vmmath/__init__.py
- pyLOM/vmmath/wrapper.py
- pyLOM/vmmath/wrapper.pyx
Adding the computation of the cell centers for unstructured meshes from the algorithm of pyAlya.
> Implementing CellCenters for Unstructured mesh

- Deps/kissfft/install_kissfft.sh
- README.md
- pyLOM/DMD/utils.py
- pyLOM/POD/utils.py
- pyLOM/SPOD/utils.py
- pyLOM/inp_out/io_h5.py
- pyLOM/mesh.py
- pyLOM/vmmath/__init__.py
- pyLOM/vmmath/src/svd.c
- pyLOM/vmmath/wrapper.py
- pyLOM/vmmath/wrapper.pyx
- pyproject.toml
- setup.py
This merge brings version 1.3.5 of pyLOM to main with the following features:
- Updated README to the project WIKI
- Fixes on dependencies: OpenBLAS and KissFFT
- Addition of the computation of cell centers
- Addition to read a desired number of modes instead of the whole matrix
- Some other minor fixes
> Latest fixes on development branch

- Deps/fftw/install_fftw.sh
- Deps/nfft/install_nfft.sh
- Deps/oneAPI/install_mkl.sh
- Examples/POD/example_POD_T280.py
Adapting pyLOM dependencies to compile in MareNostrum 5
> Adapting to compile at MareNostrum 5

- pyLOM/inp_out/io_h5.py
- pyLOM/mesh.py
- pyLOM/partition_table.py
Fixed integration with pyqvarsi. It reads eltype_linear, connectivity_linear and leinv_linear. It works with branch 14 of pyAlya, that will be pqvarsi soon.
It also gives a special treatment to empty partitions comming from  a clip done in pyqvarsi.
Tested in data from the windsor and tifon simulations
> 42 pyqvarsi integration

- pyLOM/inp_out/io_h5.py
I forgot to remove a line that is giving errors when running cases from Alya
> Small fix from previous merge

- Examples/NN/example_KAN_DLR_airfoil.py
- Examples/NN/example_KAN_xfoil_dataset.py
- Examples/NN/example_MLP_DLR_airfoil.py
- Examples/NN/example_MLP_xfoil_dataset.py
- Examples/NN/example_optuna_KAN_DLR_airfoil.py
- Examples/NN/example_optuna_MLP_DLR_airfoil.py
- Testsuite/runs/tsuite_KAN.py
- Testsuite/runs/tsuite_MLP.py
- pyLOM/NN/utils.py
> Adapting pyLOM.NN.Dataset to the new h5 file format

- README.md
- pyproject.toml
Adding python-3.12 compatibility for the pypi pipeline.
Updating README
> Fixes to new version

- Examples/NN/example_KAN_DLR_airfoil.py
- Examples/NN/example_KAN_xfoil_dataset.py
- Examples/NN/example_optuna_KAN_DLR_airfoil.py
- Testsuite/runs/tsuite_KAN.py
- pyLOM/NN/architectures/kan.py
> Added new features to KAN model

- pyLOM/NN/architectures/kan.py
This was the cause of the test failing as psutils is not a dependency of pyLOM.
> Removed psutils from imports on KAN

- pyLOM/vmmath/__init__.py
- pyLOM/vmmath/src/svd.c
- pyLOM/vmmath/src/svd.h
- pyLOM/vmmath/src/vector_matrix.c
- pyLOM/vmmath/wrapper.py
- pyLOM/vmmath/wrapper.pyx
Adding the randomized qr operation separately to the randomized svd as it is useful for GABI. Also fixed a bug on the divison between RAND MAX in the generation of a random matrix in C
> 75 randomized qr operation

- pyLOM/inp_out/io_h5.py
Introduces a small fix to allow for clipped meshes of pyQvarsi. Closes #88
> Fix save meshes nopartition

- pyLOM/NN/architectures/kan.py
- pyLOM/NN/architectures/mlp.py
> 104 bugfix mlp

- .github/workflows/build_gcc.yml
- .github/workflows/build_intel.yml
- .github/workflows/package.yml
- .github/workflows/run_testsuite.yml
- .github/workflows/run_testsuite_NN.yml
Increased version of the workflow runners.
> Modified to use python3.11.11

- .github/workflows/deploy_documentation.yml
> fixed error on deploy_documentation.yml

- Converters/alya2h5_channel.py
- Converters/alya2h5_channel_append.py
- Converters/bdf2h5.py
- Converters/ensight2h5_wing.py
- Converters/mat2h5_T280.py
- Converters/mat2h5_cylinder.py
- Converters/mat2h5_jet.py
- pyLOM/inp_out/io_h5.py
closes #115.
The script imports an additional library (pyNastran), but we assume that this is not a problem as Converters is outside pyLOM.
> Added the converter for bdf files

- pyLOM/__init__.py
- pyproject.toml
- setup.py
> Fix dynamic versioning

- pyLOM/inp_out/io_h5.py
> Fixing #144

- pyproject.toml
- requirements.txt
> Fix deprecation and updated setuptools

- docs/source/_ext/module_alias.py
- docs/source/api/pyLOM.io.rst
- docs/source/api/pyLOM.math.rst
- docs/source/api/pyLOM.rst
- docs/source/conf.py
- docs/source/installation/installation_pypi.rst
- docs/source/notebook_examples/NN/KAN_training.ipynb
> 149 update docs

- docs/source/notebook_examples/example_POD_cylinder.ipynb
Fix POD notebook so that it runs when generating the docs
> fix notebook

- Examples/example_dataset.py
- docs/source/conf.py
- docs/source/notebook_examples/example_POD_cylinder.ipynb
as it modifies just 2 lines and fixes a bug in the docs, i merge directly to main.
closes #158
> 158 bugfix docs

- Examples/NN/example_KAN_DLR_airfoil.py
- Examples/NN/example_KAN_xfoil_dataset.py
- Examples/NN/example_optuna_KAN_DLR_airfoil.py
- pyLOM/NN/__init__.py
- pyLOM/NN/architectures/kan.py
> 164 kan update

- pyproject.toml
> Adding support for cuda 11x

- pyLOM/NN/architectures/mlp.py
> 186 mlp update

- pyLOM/NN/__init__.py
- pyLOM/NN/aerodynamics.py
- pyLOM/NN/interpolator.py
> 183 adjust field

- pyLOM/NN/__init__.py
- pyLOM/NN/aerodynamics.py
- pyLOM/NN/architectures/mlp.py
- pyLOM/NN/interpolator.py
> 192 include cm adjustment

- pyLOM/utils/__init__.py
- pyLOM/utils/gpu.py
- pyLOM/vmmath/__init__.py
- pyLOM/vmmath/svd.py
- pyLOM/vmmath/svd.pyx
> New hybrid randomized QR algorithm

- pyLOM/NN/__init__.py
- pyLOM/NN/aerodynamics.py
- pyLOM/NN/interpolator.py
> 201 adjust field update
